---
# Handlers for OpenVPN role

- name: restart openvpn
  systemd:
    name: openvpn@server
    state: restarted
  become: yes

- name: reload openvpn
  systemd:
    name: openvpn@server
    state: reloaded
  become: yes
